version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ssin_db_user
      ME_CONFIG_BASICAUTH_PASSWORD: ssin_db_pw
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ssin_db_root_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: ssin_db_root_pw
    links:
      - mongo
    networks:
      - mongo-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ssin_db_root_user
      MONGO_INITDB_ROOT_PASSWORD: ssin_db_root_pw
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mongo-network

networks: 
    mongo-network:
      driver: bridge